### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SebastianGi** [SebastianGi/LoungeSimulator2017#1]
# Simulation
- [x] Think of new way to simulate
- [x] Implement simulation
# Other
- [x] Actually make it look nice
- [ ] Clean up the code
- [x] Connect Methods and Functions
